package Email;

import java.util.Scanner;

public class email {
   private String FirstName;
   private String LastName;
   private String Password;
   private int defaultLength=10;
   private String Department;
   private String email;
   private String company = "company.com";
   private int mailBoxCapacity = 500;
   private String AlternateEmail;

//Constructor to receive first name and last name.
   public email(String Firstname, String Lastname)
   {
	   this.FirstName=Firstname;
	   this.LastName=Lastname;
	   System.out.println("Email Created: "+""+this.FirstName+" "+this.LastName);
	   
	   //calling method asking for the department name.
	   this.Department = setDepartment();
	   System.out.println("Department:"+this.Department);
	   
	   //Calling a method to return a random password.
	   this.Password = randomPassword(defaultLength);
	   System.out.println("The password is: " +this.Password);
	   
	   //Now we will create a email generated by the given information.
	   email = FirstName.toLowerCase()+"."+LastName.toLowerCase() + "@" +Department+"."+company;
	   System.out.println(email);}
   
   //Ask for Department Name.
   private String setDepartment() {
	   System.out.print("Department Codes:\n1 for Accounting\n2 for Sales\n3 For Development\n0 for none.\n");
	   Scanner scan = new Scanner(System.in);
	   int deptchoice=scan.nextInt();
	   if(deptchoice==1) {
		   return "Accounting";
	   }
	   else if(deptchoice==2) {
		   return "Sales";
	   }
	   else if(deptchoice==3) {
		   return "Development";
	   }
	   else if(deptchoice==0) {
		   return "";
	   }
	   return "";
   }
   
   public int getMailBoxCapacity() {
	return mailBoxCapacity;
}

public void setMailBoxCapacity(int mailBoxCapacity) {
	this.mailBoxCapacity = mailBoxCapacity;
}

public String getAlternateEmail() {
	return AlternateEmail;
}

public void setAlternateEmail(String alternateEmail) {
	this.AlternateEmail = alternateEmail;
}

//Method for generating random password.
   private String randomPassword(int length) {
	   String setPassword="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%";
	   char[] password = new char[length];
	   for(int i=0;i<length;i++) {
		   int random = (int)(Math.random()*(setPassword.length()));
		   password[i]=setPassword.charAt(random);
	   }
	return new String(password);
   }
}
